// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/files.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePresignedUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedUrlsRequest) Reset() {
	*x = GeneratePresignedUrlsRequest{}
	mi := &file_api_proto_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedUrlsRequest) ProtoMessage() {}

func (x *GeneratePresignedUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedUrlsRequest.ProtoReflect.Descriptor instead.
func (*GeneratePresignedUrlsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_files_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePresignedUrlsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GeneratePresignedUrlsRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GeneratePresignedUrlsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GeneratePresignedUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedUrlsResponse) Reset() {
	*x = GeneratePresignedUrlsResponse{}
	mi := &file_api_proto_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedUrlsResponse) ProtoMessage() {}

func (x *GeneratePresignedUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedUrlsResponse.ProtoReflect.Descriptor instead.
func (*GeneratePresignedUrlsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_files_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePresignedUrlsResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GeneratePresignedUrlsResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GeneratePresignedUrlsResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_api_proto_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_files_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_api_proto_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_files_proto_rawDescGZIP(), []int{3}
}

var File_api_proto_files_proto protoreflect.FileDescriptor

const file_api_proto_files_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/files.proto\x12\x05proto\"n\n" +
	"\x1cGeneratePresignedUrlsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"z\n" +
	"\x1dGeneratePresignedUrlsResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x14\n" +
	"\x12DeleteFileResponse2\xb5\x01\n" +
	"\fFilesService\x12b\n" +
	"\x15GeneratePresignedUrls\x12#.proto.GeneratePresignedUrlsRequest\x1a$.proto.GeneratePresignedUrlsResponse\x12A\n" +
	"\n" +
	"DeleteFile\x12\x18.proto.DeleteFileRequest\x1a\x19.proto.DeleteFileResponseB\x17Z\x15codex-files/protob\x06proto3"

var (
	file_api_proto_files_proto_rawDescOnce sync.Once
	file_api_proto_files_proto_rawDescData []byte
)

func file_api_proto_files_proto_rawDescGZIP() []byte {
	file_api_proto_files_proto_rawDescOnce.Do(func() {
		file_api_proto_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_files_proto_rawDesc), len(file_api_proto_files_proto_rawDesc)))
	})
	return file_api_proto_files_proto_rawDescData
}

var file_api_proto_files_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_files_proto_goTypes = []any{
	(*GeneratePresignedUrlsRequest)(nil),  // 0: proto.GeneratePresignedUrlsRequest
	(*GeneratePresignedUrlsResponse)(nil), // 1: proto.GeneratePresignedUrlsResponse
	(*DeleteFileRequest)(nil),             // 2: proto.DeleteFileRequest
	(*DeleteFileResponse)(nil),            // 3: proto.DeleteFileResponse
}
var file_api_proto_files_proto_depIdxs = []int32{
	0, // 0: proto.FilesService.GeneratePresignedUrls:input_type -> proto.GeneratePresignedUrlsRequest
	2, // 1: proto.FilesService.DeleteFile:input_type -> proto.DeleteFileRequest
	1, // 2: proto.FilesService.GeneratePresignedUrls:output_type -> proto.GeneratePresignedUrlsResponse
	3, // 3: proto.FilesService.DeleteFile:output_type -> proto.DeleteFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_files_proto_init() }
func file_api_proto_files_proto_init() {
	if File_api_proto_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_files_proto_rawDesc), len(file_api_proto_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_files_proto_goTypes,
		DependencyIndexes: file_api_proto_files_proto_depIdxs,
		MessageInfos:      file_api_proto_files_proto_msgTypes,
	}.Build()
	File_api_proto_files_proto = out.File
	file_api_proto_files_proto_goTypes = nil
	file_api_proto_files_proto_depIdxs = nil
}
