// Code generated by MockGen. DO NOT EDIT.
// Source: file.go
//
// Generated by this command:
//
//	mockgen -source=file.go -destination=file_mocks.go -package=ports FileRepository,FileProvider
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gruzdev-dev/codex-files/core/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
	isgomock struct{}
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFileRepository) Create(ctx context.Context, file *domain.File) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, file)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFileRepositoryMockRecorder) Create(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFileRepository)(nil).Create), ctx, file)
}

// GetByID mocks base method.
func (m *MockFileRepository) GetByID(ctx context.Context, id string) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFileRepository)(nil).GetByID), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockFileRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockFileRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockFileRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockFileRepository) Update(ctx context.Context, file *domain.File) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, file)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFileRepositoryMockRecorder) Update(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFileRepository)(nil).Update), ctx, file)
}

// MockFileProvider is a mock of FileProvider interface.
type MockFileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFileProviderMockRecorder
	isgomock struct{}
}

// MockFileProviderMockRecorder is the mock recorder for MockFileProvider.
type MockFileProviderMockRecorder struct {
	mock *MockFileProvider
}

// NewMockFileProvider creates a new mock instance.
func NewMockFileProvider(ctrl *gomock.Controller) *MockFileProvider {
	mock := &MockFileProvider{ctrl: ctrl}
	mock.recorder = &MockFileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileProvider) EXPECT() *MockFileProviderMockRecorder {
	return m.recorder
}

// GenerateDownloadURL mocks base method.
func (m *MockFileProvider) GenerateDownloadURL(ctx context.Context, s3Path string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDownloadURL", ctx, s3Path, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDownloadURL indicates an expected call of GenerateDownloadURL.
func (mr *MockFileProviderMockRecorder) GenerateDownloadURL(ctx, s3Path, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDownloadURL", reflect.TypeOf((*MockFileProvider)(nil).GenerateDownloadURL), ctx, s3Path, ttl)
}

// GenerateUploadURL mocks base method.
func (m *MockFileProvider) GenerateUploadURL(ctx context.Context, s3Path, contentType string, maxSize int64, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUploadURL", ctx, s3Path, contentType, maxSize, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUploadURL indicates an expected call of GenerateUploadURL.
func (mr *MockFileProviderMockRecorder) GenerateUploadURL(ctx, s3Path, contentType, maxSize, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUploadURL", reflect.TypeOf((*MockFileProvider)(nil).GenerateUploadURL), ctx, s3Path, contentType, maxSize, ttl)
}
